<?php

namespace Aamant\GedBundle\Repository;

use Aamant\GedBundle\Entity\Directory;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends NestedTreeRepository
{
    public function createRoot($name, $title = null)
    {
        if (!$title) {
            $title = 'ged_'.uniqid();
        }

        $root = new Directory();
        $root->setName(strtoupper($name));
        $root->setTitle($title);

        $this->persistAsFirstChild($root);
        return $root;
    }
}
